data:
  train_dataset: "" # private train.csv path
  val_dataset: "" # private val.csv path
  test_dataset: "" # private test.csv path
  batch_size: 128
  num_workers: 4
  extra_token_num: 5
crops:
  global_crops_size: 518
model:
  n_last_blocks_list: [1, 4]
  num_classes: 1
  use_n_blocks: 4
  use_avgpool: true
  pretrained_weights: ""
  main_task: "primary_metastatic"
  backbone_ckpt_path: finetune/checkpoints/BoneFM.pth
  classifier_ckpt_path: ""
  relative_task: ["osteolytic", "osteoblastic", "type_of_primary_tumor", "pathological_fracture", "spinal_cord_compression"]
  model_ckpt_dict:
    bone_lesion: ''
    benign_malignant: ''
    primary_metastatic: ''
    osteoblastic: ''
    osteolytic: ''
    spinal_cord_compression: ''
    thrombosis: ''
    pathological_fracture: ''
    type_of_primary_tumor: ''
    hypercalcemia: ''
    lung_SCLC_or_NSCLC: ''
    lung_EGFR: ''
    lung_ROS1: ''
    lung_ALK: ''
    breast_ER: ''
    breast_PR: ''
    breast_HER2: ''
    breast_AR: ''
    renal_insufficiency: ''
optim:
  epochs: 1
  loss_type: BCE
trainer: BoneCoT_Eval_Trainer
